Updated to version 49.0
trailheadapps/easy-spaces-lwc pull request #102
Opened 2020-05-11 08:11 UTC by adityanaag3

2020-05-11 13:10 UTC, msrivastav13 approved these changes

2020-05-19 11:52 UTC, pozil commented
Jest tests will fail when CI runs.
You need to update `sfdx-lwc-jest` to the prerelease version (once the lib is [stable](https://github.com/salesforce/sfdx-lwc-jest/issues/145)).

2020-05-19 11:53 UTC, pozil requested changes
Jest tests will fail when CI runs.
You need to update `sfdx-lwc-jest` to the prerelease version (once the lib is [stable](https://github.com/salesforce/sfdx-lwc-jest/issues/145)).

2020-05-19 11:56 UTC, pozil approved these changes
Actually, I realized that there are no LWC tests so disregard my last.

2020-05-19 16:14 UTC, merged