Removed Aura Wrappers for Flows
trailheadapps/easy-spaces-lwc pull request #47
Opened 2019-10-10 09:46 UTC by adityanaag3

Updated LWC to be directly embedded in Flows, and updated the flows to use LWC instead of Aura Wrappers

2019-10-10 14:58 UTC, slychika requested changes

2019-10-10 14:58 UTC, slychika commented on es-space-mgmt/main/default/flows/createReservation.flow-meta.xml
> +    <description>Updated to LWC</description>
Create Reservation Flow with LWC.

2019-10-10 14:58 UTC, slychika commented on es-space-mgmt/main/default/flows/spaceDesigner.flow-meta.xml
> +            <name>spaceDesignFormLWC</name>
Remove LWC from name

2019-10-10 14:58 UTC, slychika commented on es-space-mgmt/main/default/flows/spaceDesigner.flow-meta.xml
> +    <description>Updated with LWC</description>
Make this a description of the component, not the tech.

2019-10-10 14:58 UTC, slychika commented on es-space-mgmt/main/default/flows/createReservation.flow-meta.xml
> +            <name>reservationHelperFormLWC</name>
remove LWC from name

2019-10-11 14:36 UTC, slychika approved these changes
Looks great, thanks for making those changes.

2019-10-11 16:46 UTC, muenzpraeger approved these changes

2019-10-11 18:56 UTC, merged